indaba/accounts/urls.py
from django.conf.urls import  include, url

from django.contrib import admin

from .views import SignUpView, LoginView, LogOutView

urlpatterns = [
    url(r'accounts/register/$', SignUpView.as_view(), name='signup'),
    url(r'accounts/login/$', LoginView.as_view(), name='login'),
    url(r'accounts/logout/$', LogOutView.as_view(), name='logout'),

]

indaba/talks/urls.py
from django.conf.urls import  url, include
from indaba.talks.views import (CreateTalk, TalkView, TalkListView,)

urlpatterns = [
    url(r'^submit_talk', CreateTalk.as_view(), name='create_talks'),
    url(r'^talks', TalkListView.as_view(), name='talks_list'),
    url(r'^(?P<pk>\d+)/$', TalkView.as_view(), name='indaba_talk'),
    ]

indaba/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^', include('indaba.talks.urls', namespace = 'talks')),
    url(r'^', include('indaba.accounts.urls', namespace='accounts')),
]

indaba/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals  import post_save
from django.dispatch  import receiver

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    contact_number = models.CharField(max_length=16, null=True, blank=True)

indaba/core/models.py
from django.db import models

class BaseProposal(models.Model):
    abstract = models.TextField()

indaba/profiles/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User)
    bio = models.TextField(max_length=600)
    phone_number = models.CharField(max_length=16)
    home_page = models.CharField(max_length=255)
    twitter_handle = models.CharField(max_length=15)
    github_username = models.CharField(max_length=32)

    def __str__(self):
        return u'%s' % self.user

indaba/talks/models.py
from django.db import models
from markitup.fields import MarkupField
from django.core.urlresolvers import reverse
from django.conf import settings


class Talk_Type(models.Model):

    talk_types = (
        ('S', "Short_Talk"),
        ('L', "Long_Talk"),
         ('T', "Tutorial"),
    )

    name = models.CharField(choices=talk_types, max_length=1)

    def __str__(self):
        return u"%s" % (self.name)


class Proposal(models.Model):

    # proposal = models.CharField(max_length=255, blank=False)
    title = models.CharField(max_length=1024)
    description = models.TextField(
        ("Brief Description"),
        max_length=400,  blank=True, # @@@ need to enforce 400 in UI
        help_text=("If your proposal is accepted this will be made public"
        " and printed in the "
        "program. Should be one paragraph, maximum 400 characters.")
    )
    abstract = models.TextField(
        ("Detailed Abstract"),
        help_text=("Detailed outline. Will be made public if your proposal is accepted. Edit "
                    "using <a href='http://daringfireball.net/projects/markdown/basics' "
                    "target='_blank'>Markdown</a>.")
    )
    talk_type = models.ForeignKey(Talk_Type)
    proposal_id = models.AutoField(primary_key=True, default=None)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="proposals", default='')
    additional_notes = models.TextField(
        ("Addtional Notes"),
        blank=True,
        help_text=("Anything else you'd like the program committee to know when making their "
                    "selection: your past experience, etc. This is not made public. Edit using "
                    "<a href='http://daringfireball.net/projects/markdown/basics' "
                    "target='_blank'>Markdown</a>.")
    )
    # meetup = models.ForeignKey()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('indaba_talk', args=(self.proposal_id,))

indaba/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit

class RegistrationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.field_class = 'col-xs-8'
        self.helper.label_class = 'col-xs-4'
        self.helper.layout = Layout(
            'username',
            'password1',
            'password2',
            ButtonHolder(
                Submit('register', 'Register', css_class='btn-primary'))

        )

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'username',
            'password',
            ButtonHolder(
                Submit('login', 'Login', css_class='btn-primary'))
        )

indaba/talks/forms.py
from indaba.talks.models import Proposal
from django import forms
from django.conf  import settings
from django.core.urlresolvers  import reverse
from django.utils.module_loading  import import_string
from django.utils.translation  import ugettext as _

from crispy_forms.bootstrap  import FormActions
from crispy_forms.helper  import FormHelper
from crispy_forms.layout  import Submit, HTML
from markitup.widgets  import MarkItUpWidget

class ProposalForm(forms.ModelForm):
    class Meta:
        model = Proposal
        fields = ('title', 'talk_type', 'description', 'abstract', 'additional_notes',)



    def __init__(self, *args, **kwargs):
        super(ProposalForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.add_input(Submit('send', 'Submit'))
        self.helper.form_class = 'form-horizontal'
        # submit_button = Submit('submit', _('Submit'))

indaba/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, FormView, RedirectView
from .forms import RegistrationForm, LoginForm
from .models import UserProfile


class SignUpView(CreateView):
    form_class = RegistrationForm
    model = UserProfile
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('home')

class LoginView(FormView):
    form_class = LoginForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('home')

    def form_valid(self,form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            return self.form_invalid(form)

        
class LogOutView(RedirectView):
    url = reverse_lazy('home')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogOutView, self).get(request, *args, **kwargs)

indaba/core/views.py
from django.shortcuts import render

# Create your views here.

indaba/profiles/views.py
from django.shortcuts import render

# Create your views here.

indaba/talks/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import (
    CreateView,
    TemplateView,
    DetailView,
    ListView,
)
from indaba.talks.models import (Talk_Type, Proposal)
from indaba.talks.forms import ProposalForm
# from .mixins import LoginRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class CreateTalk(LoginRequiredMixin, CreateView):
    model = Proposal
    form_class = ProposalForm
    template_name = "talks/talk_form.html"
    permission_denied_message = 'Please login or register to submit a talk'

    def get_permission_denied_message(self):
        return self.permission_denied_message

    def get_form_kwargs(self):
        kwargs = super(CreateTalk, self).get_form_kwargs()
        return kwargs

    def get_contex_data(self, **kwargs):
        context = super(CreateTalk, self).get_context_data(**kwargs)
        return context

    def get_form_valid_message(self):
        msg = ugettext('Talk proposal <strong>{title}</strong> created.')
        return format_html(msg, title=self.object.title)


    def form_valid(self, form):

        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()

        # Save the author information as well (many-to-many fun)
        form.save_m2m()
        return HttpResponseRedirect(self.get_success_url())

class TalkView(DetailView):
    model = Proposal
    template_name = "talks/talk.html"

    def get_object(self,*args, **kwargs):
        object = super(TalkView, self).get_object(*args, **kwargs)
        return object

    def get_contex_data(self, **kwargs):
        context = super(TalkView, self).get_contex_data(**kwargs)
        return context


class TalkListView(ListView):
    template_name = "talks/proposal_list.html"
    model = Proposal
    context_object_name = 'talks'

indaba/templates/base.html
{% load staticfiles %}
    <!DOCTYPE HTML>
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <title>PyConZim - Conference for the Python Programming Community</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Styles -->
    <link href= {% static "css/bootstrap.css" %} rel="stylesheet">
    <link href= {% static "css/style.css" %} rel="stylesheet">
    {% block static %}{% endblock %}
    <link rel='stylesheet' id='prettyphoto-css'  href= {% static "css/prettyPhoto.css" %} type='text/css' media='all'>
    <link href= {% static "css/fontello.css" %} type="text/css" rel="stylesheet">
    <!--[if lt IE 7]>
	    <link href= {% static "css/fontello-ie7.css" %} type="text/css" rel="stylesheet">
        <![endif]-->
    <!-- Google Web fonts -->
    <link href='http://fonts.googleapis.com/css?family=Quattrocento:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Patua+One' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <style>
    .regClass {
      
    }
    body {
        padding-top: 60px;
    }

    </style>
    <link href= {% static "css/bootstrap-responsive.css" %} rel="stylesheet">
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    <!-- Favicon -->
    <link rel="shortcut icon" href= {% static "img/favicon.ico" %}>
    <!-- JQuery -->
    <script type="text/javascript" src= {% static "js/jquery.js" %}></script>
    <!-- Load ScrollTo -->
    <script type="text/javascript" src= {% static "js/jquery.scrollTo-1.4.2-min.js" %}></script>
    <!-- Load LocalScroll -->
    <script type="text/javascript" src= {% static "js/jquery.localscroll-1.2.7-min.js" %}></script>
    <!-- prettyPhoto Initialization -->
    <script type="text/javascript" charset="utf-8">
          $(document).ready(function(){
            $("a[rel^='prettyPhoto']").prettyPhoto();
          });
        </script>
    </head>
    <body>
    <!--******************** NAVBAR ********************-->
    <div class="navbar-wrapper">
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
            <h1 class="brand"><a href="#top">PyConZim 2017</a></h1>
	    <!-- <h1 class="logo"><a href="#top" %}><img src= {% static "img/logo.png" %} alt="" /></a></h1> -->
            <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
            <nav class="pull-right nav-collapse collapse">
              <ul id="menu-main" class="nav">
		      <li><a title="registration" href="#registration">Registration</a></li>
                <li><a title="sponsors" href="#portfolio">Sponsors</a></li>
                <li><a title="news" href="#news">News</a></li>
                <li><a title="talks" href="#talks">Talks</a></li>
                <li><a title="coc" href="#coc">CoC</a></li>
	       	<li><a title="about" href="#about">About</a></li>


              </ul>
            </nav>
          </div>
          <!-- /.container -->
        </div>
        <!-- /.navbar-inner -->
      </div>
      <!-- /.navbar -->
    </div>
    <!-- /.navbar-wrapper -->
    <div id="top"></div>
    <!-- ******************** HeaderWrap ********************-->
   {% block content %} {% endblock %}
   <!-- Loading the javaScript at the end of the page -->
    <script type="text/javascript" src= {% static "js/bootstrap.js" %}></script>
    <script type="text/javascript" src= {% static "js/jquery.prettyPhoto.js" %}></script>
    <script type="text/javascript" src= {% static "js/site.js" %}></script>

    <!--ANALYTICS CODE-->
	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-29231762-1']);
	  _gaq.push(['_setDomainName', 'dzyngiri.com']);
	  _gaq.push(['_trackPageview']);

	  (function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>
    </body>
    </html>

indaba/templates/home.html
{% extends "base.html" %}

{% block content %}

<!-- ******************** HeaderWrap ********************-->
    <div id="headerwrap">
      <header class="clearfix">
        <!-- <h1><span>PyConZim 2017</span> The conference for the python programming community.</h1> -->
        <div class="container">
          <div class="row">
            <div class="span12">
              <h2>Join our maling list for updates</h2>
              <input type="text" name="your-email" placeholder="you@yourmail.com" class="cform-text" size="40" title="your email">
              <input type="submit" value="Notify me" class="cform-submit">
            </div>
          </div>
          <div class="row">
            <div class="span12">
              <ul class="icon">
                <li><a href="#" target="_blank"><i class="icon-twitter-circled"></i></a></li>
                <li><a href="#" target="_blank"><i class="icon-gplus-circled"></i></a></li>
                <li><a href="#" target="_blank"><i class="icon-flickr"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </header>
    </div>
<!--******************** Team Section ********************-->
    <section id="talks" class="single-page scrollblock">
      <div class="container">
        <div class="align"><i class="icon-megaphone"></i></div>
        <h1>Call For Speakers</h1>
        <!-- Five columns -->
        <div class="row">
          
          <!-- ./span2 -->
          
          
          
          
          <!-- ./span2 -->
        </div>
        <!-- /.row -->
        <div class="row">
          <div class="span10 offset1">
            <hr class="featurette-divider">
            <div class="featurette">
		    <h2 class="featurette-heading">Want to speak at Pycon Zimbabwe 2017? <span class="muted">|<a href="{% url "talks:create_talks" %}"> Please submit a talk proposal!</a></span></h2>
              <p>We are accepting proposals for talks, workshops(tutorials), sprints, and demos.</p>
              <p></p>
              <p></p>
            </div>
            <!-- /.featurette -->
            <hr class="featurette-divider">
          </div>
          <!-- .span10 -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container -->
    </section>


<!--******************** Feature ********************-->
    <!--<div class="scrollblock">-->
    <!--  <section id="feature">-->
    <!--    <div class="container">-->
    <!--      <div class="row">-->
    <!--        <div class="span12">-->
    <!--          <article>-->
    <!--            <p>PyCon Zimbabwe 2017 will be held In August in Harare.</p>-->
                
    <!--          </article>-->
    <!--        </div>-->
    <!--        <1!-- ./span12 --1>-->
    <!--      </div>-->
    <!--      <1!-- .row --1>-->
    <!--    </div>-->
    <!--    <1!-- ./container --1>-->
    <!--  </section>-->
    <!--</div>-->
    <!--<hr>-->
    <!--<1!--******************** Portfolio Section ********************--1>-->
    <section id="portfolio" class="single-page scrollblock">
      <div class="container">
        <div class="align"><i class="icon-thumbs-up"></i></div>
        <!-- Five columns -->
        <div class="row">

            <h1 class="uk-text-center uk-heading-large">Become A Sponsor</h1>
            <h2 class="uk-margin-large-top">Why we need sponsors</h2>

                <div>
                    <p>PyConZim is wholly organized by volunteers. We therefore need sponsors to help us cover the costs of:
       
                </div>
                <div>
                    
                        <li>basic running expenses;</li>
                        <li>Provide a decent location to host PyConZim;</li>
                        <li>Reimburse the travel and accommodation costs of our international speakers;</li>
                        <li>catering and refreshments;</li>
                        <li>educational materials for the tutorials;</li>
                        <li>video recording of talks!</li>
                    </ul>
                    <p>If you are interested and wish to get more information, then please contact us via <a href="mailto:zim.pycon@gmail.com">zim.pycon@gmail.com</a>.</p>
                </div>
            </div>
            <h2>Sponsor Packages</h2>
            <div class="uk-grid uk-grid-width-1-2 uk-grid-width-medium-1-4" data-uk-grid-margin>
                <div>
                    <h3>Bronze <span>($)</span></h3>
                    <ul class="uk-list uk-list-space list-icon list-icon-chevron-right">
                        <li>Small logo on the PyConZim website linked to your own website</li>
                        <li>Small logo on folders and banners</li>
                    </ul>
                </div>
                <div>
                    <h3>Silver <span>($)</span></h3>
                    <ul class="uk-list uk-list-space list-icon list-icon-chevron-right">
                        <li>Your name mentioned on the PyConZim</li>
                        <li>Medium logo on the PyZim website linked to your own website</li>
                        <li>Medium logo on folders and banners</li>
                    </ul>
                </div>
                <div>
                    <h3>Gold <span>($)</span></h3>
                    <ul class="uk-list uk-list-space list-icon list-icon-chevron-right">
                        <li>Your name mentioned on the PyConZim website</li>
                        <li>Introduction section about you on the PyCOnZim website</li>
                        <li>Big logo on the PyConZim website linked to your own website</li>
                        <li>Big logo on folders and banners</li>


                    </ul>
                </div>
                
            </div>
        </section>
    </div>
</div>

<!--******************** Team Section ********************-->
    <section id="about" class="single-page scrollblock">
      <div class="container">
        <div class="align"><i class="icon-attention"></i></div>
        <h1>About PyConZim</h1>
          <div class="span10 offset1">
            <hr class="featurette-divider">
            <div class="featurette">
              <h2 class="featurette-heading">Want to know more? <span class="muted"></span></h2>
              <p>PyCon Zimbabwe is organized by volunteers and python enthusiasts from the python programming community in Zimbabwe</p>
              <p>The first PyconZim was held from 24-25 November 2016,at the Zesa National Traing Centre. It brought delegates and speakers from the USA, South Africa, Namibia and Zimbabwe.The second edition of PyConZim is also also expected to bring speakers from Africa and the rest of the world</p>
	      <p>The two day conference will bring together students, professionals, experts and enthusiasts who wish to share their knowledge and passion about Python and related technologies. Its purpose is to increase the visibility of developers, organizations, and companies within the community. The conference is suited for all skill levels, from early beginners to expert developers. There will also be a `Django Girls Harare Workshop <http://djangogirls.org/harare>`_ during the conference.
	      </p>
            </div>
            <!-- /.featurette -->
            <hr class="featurette-divider">
          </div>
          <!-- .span10 -->
        </div>
        <!-- /.row -->
      <!-- /.container -->
    </section>

<!--******************** Contact Section ********************-->
    <section id="contact" class="single-page scrollblock">
      <div class="container">
        <div class="align"><i class="icon-mail-2"></i></div>
        <h1>Contact us now!</h1>
        <div class="row">
          <div class="span12">
            <div class="cform" id="theme-form">
              <form action="#" method="post" class="cform-form">
                <div class="row">
                  <div class="span6"> <span class="your-name">
                    <input type="text" name="your-name" placeholder="Your Name" class="cform-text" size="40" title="your name">
                    </span> </div>
                  <div class="span6"> <span class="your-email">
                    <input type="text" name="your-email" placeholder="Your Email" class="cform-text" size="40" title="your email">
                    </span> </div>
                </div>
                <div class="row">
                  <div class="span6"> <span class="company">
                    <input type="text" name="company" placeholder="Your Company" class="cform-text" size="40" title="company">
                    </span> </div>
                  <div class="span6"> <span class="website">
                    <input type="text" name="website" placeholder="Your Website" class="cform-text" size="40" title="website">
                    </span> </div>
                </div>
                <div class="row">
                  <div class="span12"> <span class="message">
                    <textarea name="message" class="cform-textarea" cols="40" rows="10" title="drop us a line."></textarea>
                    </span> </div>
                </div>
                <div>
                  <input type="submit" value="Send message" class="cform-submit pull-left">
                </div>
                <div class="cform-response-output"></div>
              </form>
            </div>
          </div>
          <!-- ./span12 -->
        </div>
        <!-- /.row -->
      </div>

{% endblock %}